version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10.0
    steps:
      - checkout
      - run: npm install
      - run: node lib/google-search-by-city/index.js world
      - add-ssh-keys:
        fingerprints:
          - "f0:bf:83:0d:7a:53:89:66:d1:2d:72:a9:85:fd:88:ab"
      - deploy:
          command: bash automated_deploy.sh
