version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10.0
    steps:
      - checkout
      - run: npm install
      - run: node lib/google-search-by-city/index.js world
      - deploy:
          command: |
            git commit -a -m "Auto-commit data update"
            git push
